servo_forward_node:
  ros__parameters:
    # 共通フレーム
    base_frame: left_arm_base_link_inertia
    tool_frame: left_armtool0

    # 向き（R=+x, L=-x）※必要に応じて変更
    direction: R

    # 進む距離[m]
    max_distance: 0.20

    # 力しきい値[N]（XY合成）
    force_limit_xy: 6.0

    # 最大速度[m/s]（力による減速係数と掛け合わせ）
    max_speed: 1.0

    # forwardでは未使用だが共通化のため置いておく（戻りの到達判定）
    back_tolerance: 0.01

servo_back_node:
  ros__parameters:
    # 共通フレーム
    base_frame: left_arm_base_link_inertia
    tool_frame: left_armtool0

    # 到達判定[m]
    back_tolerance: 0.01

    # 力しきい値[N]（XY合成）
    force_limit_xy: 6.0

    # 最大速度[m/s]（力による減速係数と掛け合わせ）
    max_speed: 1.0
